import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Layout, {siteTitle} from '../components/layout';
import Leaderboards from './leaderboards';

let devAPI = process.env.NEXT_PUBLIC_RIOT_DEV_API;
// let devAPI = JSON.stringify(process.env.NEXT_PUBLIC_RIOT_DEV_API);
export default function Home() {
  return (
    <div className={styles.container}>
      <Layout home>
        <Head>
          <meta name="description" content="Generated by create next app" />
          <title>{siteTitle}</title>
        </Head>
        <h1>Home Page</h1>
        <Leaderboards devAPI={devAPI}/>
      </Layout>
    </div>
  )
}
